### ISSUE TITLE
 I CANNOT ADD PRIME MODULES TO APP.NGPRIME.MODULE

### ISSUE THREAD

**Issue by bipper89** [NilavPatel/Ng-Prime#4]
I get the following error
ERROR in ./node_modules/primeng/components/editor/editor.js
Module not found: Error: Can't resolve 'quill' in '/ home / alvaro / WebstormProjects / Ng-Prime-master / node_modules / primeng / components / editor'

**Comment by NilavPatel** [comment]
It is an issue from PrimeNg, 

https://github.com/primefaces/primeng/issues/7769
https://forum.primefaces.org/viewtopic.php?t=48323

Please try to upgrade your PrimeNg version, if still you are facing issue let me know here.

**Comment by bipper89** [comment]
Thank you! In the node_modules/primeng/ primeng.js file, I commented on this line

__export (require ("./ components / editor / editor"));

**Comment by NilavPatel** [comment]
Thanks, I am closing this issue.
